name: Run Tests

on:
  push:
    branches:
      - main # Ajuste para a branch principal do seu projeto

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17' # Ajuste para a versão do Java necessária

      - name: Build and Test with Gradle
        run: ./gradlew clean test
